#ifndef BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_FPGA_CONTROL_PLANE_OBJECTS_H_
#define BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_FPGA_CONTROL_PLANE_OBJECTS_H_

namespace P4::P4Tools::Flay::Fpga {}  // namespace P4::P4Tools::Flay::Fpga

#endif /* BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_FPGA_CONTROL_PLANE_OBJECTS_H_ */
