#ifndef BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_NIKSS_CONTROL_PLANE_OBJECTS_H_
#define BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_NIKSS_CONTROL_PLANE_OBJECTS_H_

namespace P4::P4Tools::Flay::Nikss {}  // namespace P4::P4Tools::Flay::Nikss

#endif /* BACKENDS_P4TOOLS_MODULES_FLAY_TARGETS_NIKSS_CONTROL_PLANE_OBJECTS_H_ */
